/*package chapters.chapter_12.Checkpoints;

public class Checkpoint_13 {

    try {
        statement1;
        statement2;
        statement3;
    }
catch (Exception1 ex1) {
    }
catch (Exception2 ex2) {
    }
    statement4;
    Answer the following questions:
            ■ Will statement3 be executed?  no. because statement2 has an exception and control goes to catch statement
            ■ If the exception is not caught, will statement4 be executed?  no because an error occurs and program will abruptly terminates
            ■ If the exception is caught in the catch block, will statement4 be executed? yes
}
*/